name: Deploy Site
on:
  push:
    paths:
      - 'nodejs/**'
    branches:
      - main
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./nodejs
        publish_branch: nodejs
    - name: print-result
      run: |
        echo "${GITHUB_EVENT_NAME}"